<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logout menu</name>
   <tag></tag>
   <elementGuidId>49a825c7-b62f-46d0-aa19-528a264b4425</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[3]/div[1]/button[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[3]/div[1]/button[4]</value>
      <webElementGuid>f33b4051-7823-4898-9da8-de6f1ed609eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-logoutUser</value>
      <webElementGuid>f50bc139-0097-47e8-8c1f-6704c13f550f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
