<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>navbar</name>
   <tag></tag>
   <elementGuidId>8bc19d3a-444e-4fe4-a660-2758b0434b47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div/div/div[1]/nav/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div/div/div[1]/nav/div/button/span</value>
      <webElementGuid>1315c526-6b0e-4cf1-916e-a1a48c079cfd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
